name: todo
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.3.8
  intl: ^0.17.0
  hive_flutter: ^1.1.0
  path_provider: ^2.0.5
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  lints: 1.0.1
  build_runner: ^2.1.4
  hive_generator: ^1.1.1
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
  uses-material-design: true

fonts: 
  - family: Montserrat
    fonts: 
      - asset: assets/fonts/Montserrat-Thin.ttf
      - asset: assets/fonts/Montserrat-Light.ttf
        weight: 500
      - asset: assets/fonts/Montserrat-Bold.ttf
        weight: 800

